CODEGPT_API_KEY = "sk-1602f139-054e-469a-a56a-70a7fd2080fd"
CODEGPT_AGENT_ID = "4752b985-8222-44af-9690-f938e976760b"
CODEGPT_API_URL = "https://api.codegpt.co/api/v1/"

MISTRAL_API_KEY = "xNXPRhGcsxCbyx212CYXLD8nAU5cej82"
MISTRAL_MODEL = "ministral-3b-2410"

OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-3.5-turbo"